### ISSUE TITLE
how about provide using case in koa2?

### ISSUE THREAD

**Issue by Froguard** [mklabs/tiny-lr#111]
how about provide using case in koa2 ? thanks!

**Comment by mklabs** [comment]
Hi @Froguard I'm not familiar at all with koa. Do you mind trying to provide a use case with koa and issue a pull request ? I'd be happy to merge that :)

**Comment by Froguard** [comment]
Thanks u very much first. And I've written a little plugins which based on your tiny-lr.Named 'tinylrs'
[tinylrs] (https://github.com/Froguard/tinylrs),And it just work on my own project.Could I publish it to npm lib? I wanna use it in package.json :smile:

**Comment by mklabs** [comment]
Sure thing. You don't have to ask me if you can publish it to npm :)

That being said, you might want to take a look at https://github.com/mklabs/tiny-lr-cli seems like it shares the same features (watch & static-files). Though, yours seems lighter.

**Comment by Froguard** [comment]
That's so great, I could use it in my project, and I think the use case with koa is unnecessary.
