### ISSUE TITLE
update qs to latest version

### ISSUE THREAD

**Issue by BrandonCopley** [mklabs/tiny-lr#119]
QS has a few security issues, it would be great if QS could be updated to the latest version from qs@0.5.6 This should not break anything from my knowledge of how QS works.

**Comment by BrandonCopley** [comment]
If I pull request this in could you merge it?

**Comment by elwayman02** [comment]
👍 would be happy to review!

**Comment by elwayman02** [comment]
Release 1.0.4: https://www.npmjs.com/package/tiny-lr
