### ISSUE TITLE
Update debug package to v3.1.0

### ISSUE THREAD

**Issue by dackmin** [mklabs/tiny-lr#126]
As stated [here](https://nodesecurity.io/advisories/534), node-security is throwing Low Vulnerability issues regarding `debug` package when `< v3.1.0`.

You should consider upgrade `debug` from `v2.6.7` to `v3.1.0`.

**Comment by plroebuck** [comment]
any progress?

**Comment by brettz9** [comment]
I'm also hopeful of an update to address this security issue. Would you accept a PR?

**Comment by shama** [comment]
Looks like this was already updated 3 months ago: https://github.com/mklabs/tiny-lr/pull/129 Probably just need to clear your cache and install again.
