### ISSUE TITLE
Chrome Canary 33 requires a hardcoded snippet

### ISSUE THREAD

**Issue by joeybaker** [mklabs/tiny-lr#28]
I'm running Chrome Canary 33.0.1736.2. Which has introduced an interesting bug. Until this version (maybe a few versions previous), the following snippet worked for kicking off livereload:

```html
<script>
(function(d,t){
var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
g.src='//' + window.location.hostname + ':' + (parseInt(window.location.port, 10) + 2) + '/livereload.js';
s.parentNode.insertBefore(g,s)}(document,'script')
);
</script>
```

No longer. Now, only the following works:

```html
  <script src="//localhost:8082/livereload.js"></script>
```

**Comment by jrobeson** [comment]
is it still an issue now?

**Comment by mklabs** [comment]
Hello @te1 @joeybaker 

Like @jrobeson asked, is it still an issue ?

Closing for now, feel free to reopen if it's still an issue for you.
