### ISSUE TITLE
Use npm-shrinkwrap to avoid massive installs

### ISSUE THREAD

**Issue by mikemaccana** [mklabs/tiny-lr#30]
It's not tiny-lr's fault, but I've just installed it on a new box, and it's taken about 15 minutes to install, with a massive list of derived dependencies, including a SOCKS proxy, TLS, and coffeescript. Most of these come from mocha requiring 'ms' which seems to be huge. After 15 mins I've cancelled the install.

If you npm shrinkwrap (which I'm going to do now from a box with tiny-lr already installed), 'ms' doing silly things won't affect you.

    myapp/node_modules/tiny-lr/node_modules/noptify/node_modules/mocha/node_modules/ms/node_modules/serve/node_modules/connect/node_modules/send/node_modules/supertest/node_modules/express/node_modules/connect-redis/node_modules/redis/node_modules/underscore/node_modules/phantomjs/node_modules/unzip/node_modules/binary/node_modules/tap/lib/tap-runner.js

    myapp/node_modules/tiny-lr/node_modules/noptify/node_modules/mocha/node_modules/ms/node_modules/serve/node_modules/connect/node_modules/send/node_modules/supertest/node_modules/express/node_modules/connect-redis/node_modules/redis/node_modules/underscore/node_modules/phantomjs/node_modules/nodeunit/lib/reporters/nested.js'

    myapp/node_modules/tiny-lr/node_modules/noptify/node_modules/mocha/node_modules/ms/node_modules/serve/node_modules/connect/node_modules/send/node_modules/supertest/node_modules/express/node_modules/connect/node_modules/mime/node_modules/async_testing/lib/web-runner/public/client/lib/vendor/web-socket-js/flash-src/com/hurlant/crypto/tls

**Comment by shama** [comment]
Closing as I dont think this is an issue with tiny-lr. Please reopen if it is though. Thanks!
