### ISSUE TITLE
Question about normalizing files array

### ISSUE THREAD

**Issue by chrisyip** [mklabs/tiny-lr#34]
Server.js [L176](https://github.com/mklabs/tiny-lr/blob/master/lib/server.js#L176):

```js
// normalize files array
  files = Array.isArray(files) ? files :
    typeof files === 'string' ? files.split(/[\s,]/) :
    [];
```
`files.split(/[\s,]/)` makes path with whitespaces will cause page reloaded when CSS changed .

For example, `example project/css/style.css`:

1. files array will be `['example', 'project/css/style.css']`
2. `path.match(/\.css$/i)` will be `null`
3. `this.reloadPage()` called

Why `files.split(/[\s,]/)` is needed? I can't see any benefits of it.

**Comment by mklabs** [comment]
Hello @chrisyip 

Is it still relevant ? I agree, tiny-lr should probably split only on `,` but I'm afraid it would be a major change for those who use spaces already. So I don't know.

Closing for now, feel free to reopen if you'd like to talk more about that.

**Comment by chrisyip** [comment]
I agree with that would be a major change.

Also, because of I'm the only person who have question about it, so I think it won't be a problem for most of people :-P

Thank you for your answer.
