### ISSUE TITLE
Please add ReloadStarted and ReloadFinished events

### ISSUE THREAD

**Issue by svallory** [mklabs/tiny-lr#36]
The objective of this is to allow developers to show an reloading indicator. So, even when the new code doesn't change the appearance of the page, we'll still know it's been loaded. Perhaps a simple indicator could even be added to tiny-lr.

I can do it, if it is going to make the core. What you guys think?

**Comment by mklabs** [comment]
Hello @svallory 

If I understood you well, this is a client side issue. I don't think it's tiny-lr's role

See https://github.com/mklabs/tiny-lr/issues/51#issuecomment-111815233.

Closing for now, feel free to reopen if you'd like to talk more about that.
