### ISSUE TITLE
Poor matching of paths

### ISSUE THREAD

**Issue by eheikes** [mklabs/tiny-lr#40]
The `pickBestMatch()` / `numberOfMatchingSegments()` functions don't seem to handle cases where 2 files have the same names very well.

For example, I have `target/index.html` that includes 2 CSS files:

```html
<link rel="stylesheet" type="text/css" href="base/css/style.css">
<link rel="stylesheet" type="text/css" href="css/style.css">
```

If I change `css/style.css`, then tiny-lr reloads `base/css/style.css`, because `pickBestMatch()` considers it to be as good a match as the other (both have 2 matching path segments). This is obviously not the best match.

Is there a solution, other than renaming files? Maybe pass in the base path, or deduct score for segments that *don't* match?

**Comment by mklabs** [comment]
Hello @eheikes @maksimr 

I'm sorry, this is a client side issue and tiny-lr doesn't implement it, livereload/livereload-js does.

See https://github.com/mklabs/tiny-lr/issues/51#issuecomment-111815233

Thanks for the feedbacks anyway, I invite you to open an issue about that on livereload-js repository.

Closing for now.
