### ISSUE TITLE
using console instead of this.console causes problems when there's no console

### ISSUE THREAD

**Issue by dylang** [mklabs/tiny-lr#51]
```js
if (!(this.WebSocket = this.window.WebSocket || this.window.MozWebSocket)) {
      console.error("LiveReload disabled because the browser does not seem to support web sockets");
      return;
    }
```

This will throw an error if there isn't a `console`, such as IE when the debug tools aren't open.

`this.console` is provided for this use.

**Comment by mklabs** [comment]
Hello @dylang 

I'm sorry, as far as I can see, this is a client-side issue, and tiny-lr doesn't implement it, [livereload/livereload-js](https://github.com/livereload/livereload-js) does.

@andreyvit might help us on that

Closing for now
