### ISSUE TITLE
Options.extract does not handle missing port in URL

### ISSUE THREAD

**Issue by lcarva** [mklabs/tiny-lr#66]
When the livereload script tag does not provide a port in the URL, Options.extract falls back to 35729 which is incorrect. Instead, if no port is provided, it should use 80 for HTTP and 443 for HTTPS.

Example:
src="http://localhost/livreload.js" (Port is 80)
src="https://localhost/livreload.js" (Port is 443)

Maybe something like this:
```javascript
if (mm[2]) {
  options.port = parseInt(mm[2], 10);
} else {
  options.port = options.https ? 443 : 80
}
```

**Comment by mklabs** [comment]
Hi @lcarva 

Port 35729 is not necessarily incorrect, this is the default port for the livereload protocol.

Plus, the client-side livereload script is not part of tiny-lr anymore, but coming from livereload-js package

**Comment by lcarva** [comment]
When the browser fetches an URL that does not include the port, it'll use either 80 or 443 depending on whether or not https is being used. Sure, the default port of 35729 is the default port used by livereload, but the browser doesn't know that...
