### ISSUE TITLE
Using NPM's `livereload-js` lost the ability to use TLS connections

### ISSUE THREAD

**Issue by dahjelle** [mklabs/tiny-lr#67]
It looks like the ability to do secure websockets ([originally added here](https://github.com/mklabs/tiny-lr/commit/f97eaa57a70287dda8843e1d7aaa2ad2f577ecf9)) was lost with the switch to the NPM-published version of `livereload-js`.

**Comment by mklabs** [comment]
Hi @dahjelle,

Thank you for reporting this. I just sent [a pull request](https://github.com/mklabs/tiny-lr/pull/31) to livereload-js repo to backport the commit.

**Comment by dahjelle** [comment]
Awesome, thanks!

**Comment by ohjames** [comment]
Hi, just wondered if this issue should be closed now?

**Comment by shama** [comment]
Yep, thanks!
