### ISSUE TITLE
Implement LiveReload's Option: Override URLs to serve modified CSS from localhost?

### ISSUE THREAD

**Issue by christianmagill** [mklabs/tiny-lr#69]
http://feedback.livereload.com/knowledgebase/articles/86220-preview-css-changes-against-a-live-site-then-uplo

**Comment by mklabs** [comment]
Hello @christianmagill 

I'm sorry, I lack background on that. This is a feature of the official LiveReload application and tiny-lr goal is not to be a competitor, just a tiny lib.

I'm closing for now, feel free to reopen if you'd like to discuss more about this feature.
