### ISSUE TITLE
Middleware sets content-type for non-livereload request

### ISSUE THREAD

**Issue by jlowcs** [mklabs/tiny-lr#70]
The middleware sets the content-type to "application/json" before checking that the request is a livereload request.

https://github.com/mklabs/tiny-lr/blob/v0.1.5/lib/server.js#L118

Because of that, any request that is handled by a middleware after the tiny-lr middleware has a content-type set to "application/json".

The content-type should be set in the function that handles the specific request. Example: https://github.com/mklabs/tiny-lr/blob/v0.1.5/lib/server.js#L194

**Comment by mklabs** [comment]
Hi @jlowcs 

Thank you for the initial investigation. As far as I can see, I just have to follow your guidelines. Thanks.

**Comment by mklabs** [comment]
I need however to write a test case on that, just to be sure.

**Comment by mklabs** [comment]
https://github.com/mklabs/tiny-lr/blob/master/test/middleware.js#L46 seems to be the case, I don't understand. Anyway, I'll commit your suggestion. Seems legit.

**Comment by mklabs** [comment]
Should be ok now, thank you @jlowcs
