### ISSUE TITLE
livereload.js not found when hitting localhost:35729/livereload.js?snipver=1

### ISSUE THREAD

**Issue by F1LT3R** [mklabs/tiny-lr#71]
I run the server using the `README` example:

```javascript
var tinylr = require('tiny-lr');
 
// standard LiveReload port 
var port = 35729;
 
// tinylr(opts) => new tinylr.Server(opts); 
tinylr().listen(port, function() {
  console.log('... Listening on %s ...', port);
})
```

At first everything look as expected when I go to `localhost:35729`:

```json
{
    "tinylr": "Welcome",
    "version": "0.1.5"
}
```

But when I try to load the snippet `localhost:35729/livereload.js?snipver=1` I get `ERR_CONNECTION_REFUSED` in the browser:

```
GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED
```

...and I get 

```shell
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/@f1lt3r/node-project/node_modules/tiny-lr/node_modules/livereload-js/dist/livereload.js'
```
I look in the package directory and I can confirm that `tiny-lr` has no `livereaload-js` node module installed.

Is this expected?

**Comment by F1LT3R** [comment]
I discovered you can set the path to the script in the opts.

```javascript
var tinylr = require('tiny-lr');

var port = 35729;

var opts = {
	livereload: "path/to/livereload.js"
}

tinylr(opts).listen(port, function() {
  console.log('... Listening on %s ...', port);
});
```

Though it's not documented as far as I can tell (only checked the README so far).

It seems a little odd to me that this option has a default that does not work. Ie: in [`tiny-lr/lib/server.js`](https://github.com/mklabs/tiny-lr/blob/master/lib/server.js#L23) I can see that tiny-lr assumes the file is there by default.

I'm wondering if it's worth saving the package?

```shell
npm install livereload-js --save
```

What do you think?

**Comment by F1LT3R** [comment]
Weird... it's in the dependancies, but it's not getting installed.

```json
{
  "dependencies": {
    "body-parser": "~1.8.0",
    "debug": "~2.0.0",
    "faye-websocket": "~0.7.2",
    "livereload-js": "^2.2.0",
    "parseurl": "~1.3.0",
    "qs": "~2.2.3"
  }
```

**Comment by mklabs** [comment]
Hello @F1LT3R 

What is the status on this issue, still relevant ?

> Though it's not documented as far as I can tell (only checked the README so far).

Yes, it should be documented, I'll try to document it later today.

**Comment by mklabs** [comment]
I'm closing for now, feel free to reopen if it's still relevant.

**Comment by redox** [comment]
I'm still experiencing the issue with `tiny-lr@0.1.6`. The `livereload-js` package is not installed in `node_modules/tiny-lr/node_modules/livereload-js/dist/livereload.js` as it should be.

I'm using `npm@3.1.0`.

You can reproduce the issue with:

```
git clone https://github.com:algolia/algoliasearch-boilerplate.git
cd algoliasearch-boilerplate
npm install
gulp
```

it will crash with:

```
[15:46:21] Using gulpfile ~/.................../algoliasearch-boilerplate/gulpfile.js
[15:46:21] Starting 'views'...
[15:46:21] Finished 'views' after 5.49 ms
[15:46:21] Starting 'images'...
[15:46:21] Finished 'images' after 3.83 ms
[15:46:21] Starting 'scripts'...
[15:46:21] Finished 'scripts' after 955 μs
[15:46:21] Starting 'styles'...
[15:46:21] Finished 'styles' after 3.13 ms
[15:46:21] Starting 'lint'...
[15:46:21] Finished 'lint' after 3.74 ms
[15:46:21] Starting 'build'...
[15:46:21] Finished 'build' after 5.27 μs
[15:46:21] Starting 'watch'...
[15:46:21] Finished 'watch' after 34 ms
[15:46:21] Starting 'open-browser'...
[15:46:21] Finished 'open-browser' after 4.12 ms
[15:46:21] Starting 'default'...
[15:46:21] Finished 'default' after 7.79 μs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open '/Users/r.................../algoliasearch-boilerplate/node_modules/tiny-lr/node_modules/livereload-js/dist/livereload.js'
```
