### ISSUE TITLE
Livereload not exiting after command called

### ISSUE THREAD

**Issue by iamdriz** [mklabs/tiny-lr#73]
So I have the following in a bat file:

~~~
node livereload.js
grunt watch
~~~

and my livereload.js file looks like:

~~~
var lrserver = require('tiny-lr')();
lrserver.listen(35729, function(err) {
	console.log('LR Server Started');
});
~~~

But because the livereload.js doesn't exit after it's run, I don't see any of the console.logs sent from the watch task! If I do it inside the cmd prompt by hand, I have to do CTRL+C to see them (the grunt command is being run, just that the cmd prompt is stuck with _ on the livereload command)

![image](https://cloud.githubusercontent.com/assets/801252/6559885/e6f2692e-c67d-11e4-9f42-12c63c425c90.png)

Why isn't the server command exiting so I can run another command?

**Comment by shama** [comment]
Like `grunt watch`, the server process needs to continue running listening for connections. Thus it will stay open until you tell it to close.

On windows you can tell a process to run in the background with `START /B program`.
