### ISSUE TITLE
Should this module be deprecated ?

### ISSUE THREAD

**Issue by MoOx** [mklabs/tiny-lr#74]
Original tiny-lr seems to alive contrary to your module https://github.com/mklabs/tiny-lr

**Comment by shama** [comment]
-1 Why deprecate modules that work?

**Comment by MoOx** [comment]
Oups. I was thinking I were opening an issue on your fork @shama https://github.com/shama/tiny-lr.
I think you should deprecate this one in favor of the original one mklabs/tiny-lr.

**Comment by shama** [comment]
Ah ok, yep I will deprecate my fork in favor of this one soon.

**Comment by mklabs** [comment]
Hello @MoOx can I close this issue then ?

**Comment by MoOx** [comment]
Yep
