### ISSUE TITLE
Question: Is it possible to send `error` command to clients?

### ISSUE THREAD

**Issue by mctep** [mklabs/tiny-lr#76]
Hello! Thank you for your job.

Sometimes compilation ends with errors and target files are not changed, so page is not reloaded. And I should go to shell console for looking for what happens.

Is it possible to add in tyny-lr `error` command for clients? Expample:

```js
// client.js
Client.prototype.errors = function reload(errors) {
  errors.forEach(function(error) {
    this.send({
      command: 'error',
      message: error.message
    });
  }, this);
};
```

```sh
# send error
curl http://localhost:35729/error?message=Unexpected%20indetifier%20in%20my_script.js:20
```

```js
// listen error in browser
LiveReload.on('errors', function(errors) {
  // I handle errors, throw to console or other stuff
});
```

**Comment by jrobeson** [comment]
this might help: https://github.com/mklabs/tiny-lr/commit/cd8aef356266cbe67e89c2c6e218f60e9721e4d6

**Comment by mklabs** [comment]
Hello @mctep @jrobeson 

Sure, I think it's possible. I'm not sure however if it's compatible with LiveReload protocol

**Comment by mklabs** [comment]
http://feedback.livereload.com/knowledgebase/articles/86174-livereload-protocol

**Comment by mklabs** [comment]
- We would need to add a new route: https://github.com/mklabs/tiny-lr/blob/master/lib/server.js#L25
- Parse the `message` param

For 

```js
// listen error in browser
LiveReload.on('errors', function(errors) {
  // I handle errors, throw to console or other stuff
});
```

How would you do that ? Manually or something that would need to be introduced in [livereload/livereload-js](https://github.com/livereload/livereload-js). I think you mean "manually" but just to be sure.

There is also the notion of livereload-js plugins that might be worth checking out.

**Comment by mctep** [comment]
Hello!

Thank you for links. I've investigated the issue and got an overview :-)

> I'm not sure however if it's compatible with LiveReload protocol
> http://feedback.livereload.com/knowledgebase/articles/86174-livereload-protocol

There is section about `alert requests` in `Official Protocol Version 7`. I think it is just what's needed.

> Alert request, server-to-client, can be used by console servers to announce important things (like 'Upgrade your browser extension!') to the user.
> ```
>  {
>      command: 'alert',
>      message: 'HEY!'
>  }
>```

In the `livereload.js` code this request calls `window.alert` function [livereload.coffee#L99](https://github.com/livereload/livereload-js/blob/e1d943628005ad8d18a50ee1e8c29858ca748d10/src/livereload.coffee#L99):
```coffee
class LiveReload
  ...
  performAlert: (message) ->
    alert message.message
```

But I want to do something else:
```js
// myscript
LiveReload.options.handleAlert = function(message) {
    // just as example
    $('#my-error-red-block').text(message).show();
};
```

So I think there are two issues. In `tyny-lr` add a new route for `alert` command.

And add to `livereload-js` alert handler like this:

```coffee
# livereload.coffee
performAlert: (message) ->
    if (typeof @options.handleAlert == 'function') {
        return @options.handleAlert message.message
    }
    # alert by default
    alert message.message
```

**Comment by mctep** [comment]
Or. We can hack the second issue by redefining the orignal method...

But it is not good... ~~But it is JavaScript!~~ :-)

```js
// myscript.js
LiveReload.constructor.prototype.performAlert = function(message) {
    // evil mode on
};
```
