### ISSUE TITLE
Strict mime type checking causes Content-Type for localhost/livereload.js?snipver=1 to fail

### ISSUE THREAD

**Issue by henrytseng** [mklabs/tiny-lr#77]
It looks like when strict mime type checking is enabled a request for the `livereload.js` script is failing.  

It is served up the `Content-Type` being `application/json` which is not executable when it should be served up with `application/javascript`.

**Comment by shama** [comment]
Fixed by 46a474a02bc724713a3a7766457ca0c6417920f9 Thanks!
