### ISSUE TITLE
tag a new release?

### ISSUE THREAD

**Issue by jrobeson** [mklabs/tiny-lr#79]
There's been a few fixes since the last release. Especially the EADDRINUSE fix.

**Comment by mklabs** [comment]
Hello @jrobeson You're right. I'll take care of that tomorrow

**Comment by jrobeson** [comment]
consider this PR first, if you don't mind. https://github.com/mklabs/tiny-lr/pull/80

**Comment by mklabs** [comment]
Sure, I'll do.

**Comment by mklabs** [comment]
0.1.6 released, thanks @jrobeson 

https://github.com/mklabs/tiny-lr/compare/v0.1.5...v0.1.6
