### ISSUE TITLE
Too much CPU usage

### ISSUE THREAD

**Issue by tusharmath** [mklabs/tiny-lr#84]
I am using this module https://github.com/Calvein/serveur, to run a static website which inturn is using tiny-lr.

CPU usage turns out to go really high because of this module.
![screen shot 2015-06-28 at 2 51 54 pm](https://cloud.githubusercontent.com/assets/194482/8395810/41aabcbc-1da5-11e5-97aa-a6e8ab2df71a.png)

Otherwise, without livereload
![screen shot 2015-06-28 at 2 54 16 pm](https://cloud.githubusercontent.com/assets/194482/8395816/9f02bb76-1da5-11e5-92b1-e47459292dcd.png)

cc: @calvein
My understanding is that you are watching over everything and there is no way to control.
https://github.com/Calvein/serveur/blob/master/bin/serveur#L169

**Comment by mklabs** [comment]
tiny-lr itself doesn't do file watch, this is likely because of the wrapper you're using (maybe because it watches node_modules)
