### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by myndzi** [mklabs/tiny-lr#88]
This commit:
https://github.com/mklabs/tiny-lr/commit/5754e8cc0ac2b430c78b265a84b459b054aaa889

fixes my problem, but it is 24 days old and hasn't been published to npm. Please publish a new version?

**Comment by Anahkiasen** [comment]
Same here.

**Comment by smrq** [comment]
+1 (the most helpful of comments)

**Comment by stevelacy** [comment]
Please 
All npm 3+ Break on this

:+1:

**Comment by shama** [comment]
Published and sorry for the delay!
