### ISSUE TITLE
AngularJS / Partials

### ISSUE THREAD

**Issue by Iristyle** [mklabs/tiny-lr#9]
Not sure how to handle this exactly, and haven't really dug in on it, but figured I would bring it up for discussion.

When building apps with AngularJS, its common to use partial html pages to build out blocks of UI, and angular can load those at runtime. (There is also some support within requirejs-glob to load templates using RequireJS, but we're not using that quite yet.)

I'm finding that livereload sometimes ends up loading a blank page when it's notified that a partial changes.  Part of this is probably on the `grunt-regarde` side of the fence, but there might be something to address in `tiny-lr` as well.

I'm actually seeing 2 things in my console output.  I've set `regarde` to monitor my entire `generated` folder.

* When files are compiled / copied over to `generated`, there are a bunch of extra notifications for things that were copied in, but didn't actually change.  I'm not sure that there's even a great way to address this, other than to just build a distribution version of everything and monitor just a few files (and of course, this is a bunch slower)

For instance, here's some sample output.

```
Running "regarde" task
File generated\css added. Tasks: livereload
File generated\data added. Tasks: livereload
File generated\font added. Tasks: livereload
File generated\img added. Tasks: livereload
File generated\js added. Tasks: livereload
File generated\lib added. Tasks: livereload
File generated\partials added. Tasks: livereload
File generated\partials\includes added. Tasks: livereload

Running "livereload" task
... Reloading generated\css, generated\data, generated\font, generated\img, generated\js, generated\lib, generated\partials, generated\partials\includes ...
... Reload generated\css ...
... Reload generated\data ...
... Reload generated\font ...
... Reload generated\img ...
... Reload generated\js ...
... Reload generated\lib ...
... Reload generated\partials ...
... Reload generated\partials\includes ...

Running "regarde" task
File generated\partials\profile-bio-cert-insurance.html changed. Tasks: livereload

Running "livereload" task
... Reloading generated\partials\profile-bio-cert-insurance.html ...
... Reload generated\partials\profile-bio-cert-insurance.html ...
```

* Sometimes a partial reloads OK, sometimes the web page just goes blank when LiveReload kicks in, and I have to force it to reload with a `Ctrl-F5` instead.

So I'm not sure if the best approach here is to pass an extra flag to change how things are reloaded in the browser snippet portion of livereload?

FYI Angular guys - we're __not__ using `html5mode`

/cc @vojtajina @IgorMinar @btford @tkellen @sindresorhus

**Comment by mklabs** [comment]
Hello @Iristyle 

Is it still an issue for you ? Sorry for the 2 years delay.

I'm closing for now, feel free to reopen if you'd like to talk more about that.
