### ISSUE TITLE
not compatible with npm@3.x

### ISSUE THREAD

**Issue by fish520** [mklabs/tiny-lr#91]
in `lib/server.js`:

```javascript
options.livereload = options.livereload || path.join(__dirname, '../node_modules/livereload-js/dist/livereload.js');
```

This is what makes the gulp-livereload plugin sucks.

**Comment by scaljeri** [comment]
+1

**Comment by boxfoot** [comment]
I just went to submit a PR to fix this, and saw that it's already fixed by https://github.com/mklabs/tiny-lr/commit/5754e8cc0ac2b430c78b265a84b459b054aaa889.  Thanks @benelsen !

**Comment by christophehurpeau** [comment]
+1

**Comment by inuscript** [comment]
+1

**Comment by Sinewyk** [comment]
any reasons why there's no tag & npm release ?

**Comment by teltploek** [comment]
+1

**Comment by Rowno** [comment]
npm 3 has come out of beta, so a lot of people are going to start running into this bug unless the fix is published.

**Comment by mlegenhausen** [comment]
+1

**Comment by nickdesaulniers** [comment]
bump :+1:

**Comment by phparkle** [comment]
+1

**Comment by flyingmutant** [comment]
Guys, can you please release a new version with the fix included?

**Comment by mgechev** [comment]
+1

**Comment by lukehorvat** [comment]
Pretty please.

**Comment by elwayman02** [comment]
@lukehorvat https://github.com/elwayman02/mini-lr

**Comment by lukehorvat** [comment]
@elwayman02 Thanks for getting that merged into gulp-livereload. :)

**Comment by elwayman02** [comment]
np @lukehorvat glad to help! :)

**Comment by shama** [comment]
Sorry for the delay everyone! I'll try and take a more active role in maintaining tiny-lr going forward. Also I'd be happy to give commit access to any contributors to help maintain to avoid this in the future (unless @mklabs objects to this idea).

`0.1.7` was published with the npm3 fix. Thanks for being patient!
